name: release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.jar
            
  publish:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
        
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          
      - name: Build with maven
        run: mvn -B package --file pom.xml
        
      - name: Publish package
        run: mvn --batch-mode deploy -DskipUTs=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
